services:

  grafana:
    image: grafana/grafana:13.2.0
    container_name: enterprise-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    networks:
      - enterprise-ai-net

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: enterpriseai
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 5s

    volumes:
      - enterprise-grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./provisioning/alerting:/etc/grafana/provisioning/alerting:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro

volumes:
  enterprise-grafana-data:
    external: true

networks:
  enterprise-ai-net:
    external: true
