from prometheus_client import Counter, Gauge, Histogram


# -------------------------------------------------------------------
# Request metrics
# -------------------------------------------------------------------

LLM_REQUESTS_TOTAL = Counter(
    "llm_requests_total",
    "Total number of LLM generation requests.",
    [
        "requested_model",
        "selected_model",
        "status",
    ],
)


LLM_GENERATION_DURATION_SECONDS = Histogram(
    "llm_request_duration_seconds",
    "LLM generation request latency in seconds.",
    [
        "selected_model",
    ],
)


LLM_GENERATION_FAILURES_TOTAL = Counter(
    "llm_generation_failures_total",
    "Total number of failed LLM generation requests.",
    [
        "selected_model",
    ],
)


# -------------------------------------------------------------------
# Token telemetry
# -------------------------------------------------------------------

LLM_INPUT_TOKENS_TOTAL = Counter(
    "llm_input_tokens_total",
    "Total number of input tokens processed by the runtime.",
    [
        "selected_model",
    ],
)


LLM_OUTPUT_TOKENS_TOTAL = Counter(
    "llm_output_tokens_total",
    "Total number of output tokens generated by the runtime.",
    [
        "selected_model",
    ],
)


LLM_TOKENS_TOTAL = Counter(
    "llm_tokens_total",
    "Total number of input and output tokens processed.",
    [
        "selected_model",
    ],
)

# -------------------------------------------------------------------
# Cost telemetry
# -------------------------------------------------------------------

LLM_ESTIMATED_COST_USD_TOTAL = Counter(
    "llm_estimated_cost_usd_total",
    "Estimated self-hosted inference compute cost in USD.",
    [
       "selected_model",
    ],
)


# -------------------------------------------------------------------
# Routing metrics
# -------------------------------------------------------------------

LLM_ROUTING_DECISIONS_TOTAL = Counter(
    "llm_routing_decisions_total",
    "Total number of automatic model routing decisions.",
    [
        "requested_model",
        "selected_model",
    ],
)


LLM_ROUTING_CAPACITY_OVERRIDES_TOTAL = Counter(
    "llm_routing_capacity_overrides_total",
    "Total number of automatic routing decisions overridden by token capacity.",
    [
        "from_model",
        "to_model",
    ],
)


LLM_ROUTING_CAPACITY_REJECTIONS_TOTAL = Counter(
    "llm_routing_capacity_rejections_total",
    "Total number of routing requests rejected because of token capacity.",
    [
        "requested_model",
    ],
)


LLM_ROUTING_SELECTED_MODELS_TOTAL = Counter(
    "llm_routing_selected_models_total",
    "Total number of requests by final selected model.",
    [
        "selected_model",
    ],
)


LLM_ROUTING_OUTCOMES_TOTAL = Counter(
    "llm_routing_outcomes_total",
    "Total number of routing decisions by outcome.",
    [
        "outcome",
    ],
)


LLM_ROUTING_SCORE = Gauge(
    "llm_routing_score",
    "Latest multi-signal routing score by model.",
    [
        "model",
    ],
)


LLM_ROUTING_SCORE_MARGIN = Gauge(
    "llm_routing_score_margin",
    "Latest absolute difference between multi-signal model scores.",
)


# -------------------------------------------------------------------
# Backend health
# -------------------------------------------------------------------

LLM_BACKEND_UP = Gauge(
    "llm_backend_up",
    "Backend availability. 1 = available, 0 = unavailable.",
    [
        "backend",
    ],
)


# -------------------------------------------------------------------
# Model registry
# -------------------------------------------------------------------

LLM_MODELS_CONFIGURED = Gauge(
    "llm_models_configured",
    "Number of models configured in the runtime model registry.",
)


# -------------------------------------------------------------------
# Runtime state
# -------------------------------------------------------------------

LLM_RUNTIME_UP = Gauge(
    "llm_runtime_up",
    "Runtime API availability. Always 1 while the process is healthy.",
)

LLM_RUNTIME_UP.set(1)
