FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV MODEL_ROOT=/models

WORKDIR /app

COPY requirements-vllm.txt .

RUN pip install --no-cache-dir \
    -r requirements-vllm.txt

COPY app ./app

EXPOSE 8000

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
